/*
 * products
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Products.Api.Attributes;
using Products.Api.Security;
using Microsoft.AspNetCore.Authorization;
using Products.Api.Models;

namespace Products.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// Add Product
        /// </summary>
        /// <remarks>Create a new product.</remarks>
        /// <param name="product"></param>
        /// <response code="201"></response>
        [HttpPost]
        [Route("/v1/products")]
        [Authorize(AuthenticationSchemes = ApiKeyAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("AddProduct")]
        [SwaggerResponse(statusCode: 201, type: typeof(Product), description: "")]
        public virtual IActionResult AddProduct([FromBody]Product product)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(Product));

            string exampleJson = null;
            exampleJson = "{\n  \"id\" : 0,\n  \"name\" : \"string\",\n  \"inventoryCount\" : 0,\n  \"costPerUnit\" : 0.4510864935400465\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Product>(exampleJson)
            : default(Product);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
